// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: srpc.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "srpc.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace srpc {
namespace types {
class SrpcMessageHeaderDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<SrpcMessageHeader> {
} _SrpcMessageHeader_default_instance_;
class SrpcStringDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<SrpcString> {
} _SrpcString_default_instance_;
class SrpcStringListDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<SrpcStringList> {
} _SrpcStringList_default_instance_;

namespace protobuf_srpc_2eproto {


namespace {

::google::protobuf::Metadata file_level_metadata[3];
const ::google::protobuf::EnumDescriptor* file_level_enum_descriptors[2];

}  // namespace

const ::google::protobuf::uint32 TableStruct::offsets[] = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SrpcMessageHeader, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SrpcMessageHeader, type_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SrpcMessageHeader, mid_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SrpcMessageHeader, rid_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SrpcMessageHeader, nature_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SrpcString, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SrpcString, string_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SrpcStringList, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SrpcStringList, string_),
};

static const ::google::protobuf::internal::MigrationSchema schemas[] = {
  { 0, -1, sizeof(SrpcMessageHeader)},
  { 8, -1, sizeof(SrpcString)},
  { 13, -1, sizeof(SrpcStringList)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&_SrpcMessageHeader_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&_SrpcString_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&_SrpcStringList_default_instance_),
};

namespace {

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "srpc.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, file_level_enum_descriptors, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 3);
}

}  // namespace

void TableStruct::Shutdown() {
  _SrpcMessageHeader_default_instance_.Shutdown();
  delete file_level_metadata[0].reflection;
  _SrpcString_default_instance_.Shutdown();
  delete file_level_metadata[1].reflection;
  _SrpcStringList_default_instance_.Shutdown();
  delete file_level_metadata[2].reflection;
}

void TableStruct::InitDefaultsImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::internal::InitProtobufDefaults();
  _SrpcMessageHeader_default_instance_.DefaultConstruct();
  _SrpcString_default_instance_.DefaultConstruct();
  _SrpcStringList_default_instance_.DefaultConstruct();
}

void InitDefaults() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &TableStruct::InitDefaultsImpl);
}
void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] = {
      "\n\nsrpc.proto\022\nsrpc.types\"\226\002\n\021SrpcMessage"
      "Header\0227\n\004type\030\001 \001(\0162).srpc.types.SrpcMe"
      "ssageHeader.MessageType\022\013\n\003mid\030\002 \001(\005\022\013\n\003"
      "rid\030\003 \001(\005\022;\n\006nature\030\004 \001(\0162+.srpc.types.S"
      "rpcMessageHeader.MessageNature\">\n\013Messag"
      "eType\022\013\n\007UNKNOWN\020\000\022\n\n\006METHOD\020\001\022\n\n\006RESULT"
      "\020\002\022\n\n\006SIGNAL\020\003\"1\n\rMessageNature\022\013\n\007DEFAU"
      "LT\020\000\022\010\n\004SYNC\020\001\022\t\n\005ASYNC\020\002\"\034\n\nSrpcString\022"
      "\016\n\006string\030\001 \001(\t\" \n\016SrpcStringList\022\016\n\006str"
      "ing\030\001 \003(\tb\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 377);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "srpc.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::OnShutdown(&TableStruct::Shutdown);
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;

}  // namespace protobuf_srpc_2eproto

const ::google::protobuf::EnumDescriptor* SrpcMessageHeader_MessageType_descriptor() {
  protobuf_srpc_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_srpc_2eproto::file_level_enum_descriptors[0];
}
bool SrpcMessageHeader_MessageType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
      return true;
    default:
      return false;
  }
}

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const SrpcMessageHeader_MessageType SrpcMessageHeader::UNKNOWN;
const SrpcMessageHeader_MessageType SrpcMessageHeader::METHOD;
const SrpcMessageHeader_MessageType SrpcMessageHeader::RESULT;
const SrpcMessageHeader_MessageType SrpcMessageHeader::SIGNAL;
const SrpcMessageHeader_MessageType SrpcMessageHeader::MessageType_MIN;
const SrpcMessageHeader_MessageType SrpcMessageHeader::MessageType_MAX;
const int SrpcMessageHeader::MessageType_ARRAYSIZE;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900
const ::google::protobuf::EnumDescriptor* SrpcMessageHeader_MessageNature_descriptor() {
  protobuf_srpc_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_srpc_2eproto::file_level_enum_descriptors[1];
}
bool SrpcMessageHeader_MessageNature_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const SrpcMessageHeader_MessageNature SrpcMessageHeader::DEFAULT;
const SrpcMessageHeader_MessageNature SrpcMessageHeader::SYNC;
const SrpcMessageHeader_MessageNature SrpcMessageHeader::ASYNC;
const SrpcMessageHeader_MessageNature SrpcMessageHeader::MessageNature_MIN;
const SrpcMessageHeader_MessageNature SrpcMessageHeader::MessageNature_MAX;
const int SrpcMessageHeader::MessageNature_ARRAYSIZE;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int SrpcMessageHeader::kTypeFieldNumber;
const int SrpcMessageHeader::kMidFieldNumber;
const int SrpcMessageHeader::kRidFieldNumber;
const int SrpcMessageHeader::kNatureFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

SrpcMessageHeader::SrpcMessageHeader()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_srpc_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:srpc.types.SrpcMessageHeader)
}
SrpcMessageHeader::SrpcMessageHeader(const SrpcMessageHeader& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&type_, &from.type_,
    reinterpret_cast<char*>(&nature_) -
    reinterpret_cast<char*>(&type_) + sizeof(nature_));
  // @@protoc_insertion_point(copy_constructor:srpc.types.SrpcMessageHeader)
}

void SrpcMessageHeader::SharedCtor() {
  ::memset(&type_, 0, reinterpret_cast<char*>(&nature_) -
    reinterpret_cast<char*>(&type_) + sizeof(nature_));
  _cached_size_ = 0;
}

SrpcMessageHeader::~SrpcMessageHeader() {
  // @@protoc_insertion_point(destructor:srpc.types.SrpcMessageHeader)
  SharedDtor();
}

void SrpcMessageHeader::SharedDtor() {
}

void SrpcMessageHeader::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* SrpcMessageHeader::descriptor() {
  protobuf_srpc_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_srpc_2eproto::file_level_metadata[0].descriptor;
}

const SrpcMessageHeader& SrpcMessageHeader::default_instance() {
  protobuf_srpc_2eproto::InitDefaults();
  return *internal_default_instance();
}

SrpcMessageHeader* SrpcMessageHeader::New(::google::protobuf::Arena* arena) const {
  SrpcMessageHeader* n = new SrpcMessageHeader;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void SrpcMessageHeader::Clear() {
// @@protoc_insertion_point(message_clear_start:srpc.types.SrpcMessageHeader)
  ::memset(&type_, 0, reinterpret_cast<char*>(&nature_) -
    reinterpret_cast<char*>(&type_) + sizeof(nature_));
}

bool SrpcMessageHeader::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:srpc.types.SrpcMessageHeader)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // .srpc.types.SrpcMessageHeader.MessageType type = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u)) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_type(static_cast< ::srpc::types::SrpcMessageHeader_MessageType >(value));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 mid = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &mid_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 rid = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &rid_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .srpc.types.SrpcMessageHeader.MessageNature nature = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(32u)) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_nature(static_cast< ::srpc::types::SrpcMessageHeader_MessageNature >(value));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:srpc.types.SrpcMessageHeader)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:srpc.types.SrpcMessageHeader)
  return false;
#undef DO_
}

void SrpcMessageHeader::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:srpc.types.SrpcMessageHeader)
  // .srpc.types.SrpcMessageHeader.MessageType type = 1;
  if (this->type() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      1, this->type(), output);
  }

  // int32 mid = 2;
  if (this->mid() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->mid(), output);
  }

  // int32 rid = 3;
  if (this->rid() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(3, this->rid(), output);
  }

  // .srpc.types.SrpcMessageHeader.MessageNature nature = 4;
  if (this->nature() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      4, this->nature(), output);
  }

  // @@protoc_insertion_point(serialize_end:srpc.types.SrpcMessageHeader)
}

::google::protobuf::uint8* SrpcMessageHeader::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic;  // Unused
  // @@protoc_insertion_point(serialize_to_array_start:srpc.types.SrpcMessageHeader)
  // .srpc.types.SrpcMessageHeader.MessageType type = 1;
  if (this->type() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      1, this->type(), target);
  }

  // int32 mid = 2;
  if (this->mid() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->mid(), target);
  }

  // int32 rid = 3;
  if (this->rid() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(3, this->rid(), target);
  }

  // .srpc.types.SrpcMessageHeader.MessageNature nature = 4;
  if (this->nature() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      4, this->nature(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:srpc.types.SrpcMessageHeader)
  return target;
}

size_t SrpcMessageHeader::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:srpc.types.SrpcMessageHeader)
  size_t total_size = 0;

  // .srpc.types.SrpcMessageHeader.MessageType type = 1;
  if (this->type() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->type());
  }

  // int32 mid = 2;
  if (this->mid() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->mid());
  }

  // int32 rid = 3;
  if (this->rid() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->rid());
  }

  // .srpc.types.SrpcMessageHeader.MessageNature nature = 4;
  if (this->nature() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->nature());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void SrpcMessageHeader::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:srpc.types.SrpcMessageHeader)
  GOOGLE_DCHECK_NE(&from, this);
  const SrpcMessageHeader* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const SrpcMessageHeader>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:srpc.types.SrpcMessageHeader)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:srpc.types.SrpcMessageHeader)
    MergeFrom(*source);
  }
}

void SrpcMessageHeader::MergeFrom(const SrpcMessageHeader& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:srpc.types.SrpcMessageHeader)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from.type() != 0) {
    set_type(from.type());
  }
  if (from.mid() != 0) {
    set_mid(from.mid());
  }
  if (from.rid() != 0) {
    set_rid(from.rid());
  }
  if (from.nature() != 0) {
    set_nature(from.nature());
  }
}

void SrpcMessageHeader::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:srpc.types.SrpcMessageHeader)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SrpcMessageHeader::CopyFrom(const SrpcMessageHeader& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:srpc.types.SrpcMessageHeader)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SrpcMessageHeader::IsInitialized() const {
  return true;
}

void SrpcMessageHeader::Swap(SrpcMessageHeader* other) {
  if (other == this) return;
  InternalSwap(other);
}
void SrpcMessageHeader::InternalSwap(SrpcMessageHeader* other) {
  std::swap(type_, other->type_);
  std::swap(mid_, other->mid_);
  std::swap(rid_, other->rid_);
  std::swap(nature_, other->nature_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata SrpcMessageHeader::GetMetadata() const {
  protobuf_srpc_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_srpc_2eproto::file_level_metadata[0];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// SrpcMessageHeader

// .srpc.types.SrpcMessageHeader.MessageType type = 1;
void SrpcMessageHeader::clear_type() {
  type_ = 0;
}
::srpc::types::SrpcMessageHeader_MessageType SrpcMessageHeader::type() const {
  // @@protoc_insertion_point(field_get:srpc.types.SrpcMessageHeader.type)
  return static_cast< ::srpc::types::SrpcMessageHeader_MessageType >(type_);
}
void SrpcMessageHeader::set_type(::srpc::types::SrpcMessageHeader_MessageType value) {
  
  type_ = value;
  // @@protoc_insertion_point(field_set:srpc.types.SrpcMessageHeader.type)
}

// int32 mid = 2;
void SrpcMessageHeader::clear_mid() {
  mid_ = 0;
}
::google::protobuf::int32 SrpcMessageHeader::mid() const {
  // @@protoc_insertion_point(field_get:srpc.types.SrpcMessageHeader.mid)
  return mid_;
}
void SrpcMessageHeader::set_mid(::google::protobuf::int32 value) {
  
  mid_ = value;
  // @@protoc_insertion_point(field_set:srpc.types.SrpcMessageHeader.mid)
}

// int32 rid = 3;
void SrpcMessageHeader::clear_rid() {
  rid_ = 0;
}
::google::protobuf::int32 SrpcMessageHeader::rid() const {
  // @@protoc_insertion_point(field_get:srpc.types.SrpcMessageHeader.rid)
  return rid_;
}
void SrpcMessageHeader::set_rid(::google::protobuf::int32 value) {
  
  rid_ = value;
  // @@protoc_insertion_point(field_set:srpc.types.SrpcMessageHeader.rid)
}

// .srpc.types.SrpcMessageHeader.MessageNature nature = 4;
void SrpcMessageHeader::clear_nature() {
  nature_ = 0;
}
::srpc::types::SrpcMessageHeader_MessageNature SrpcMessageHeader::nature() const {
  // @@protoc_insertion_point(field_get:srpc.types.SrpcMessageHeader.nature)
  return static_cast< ::srpc::types::SrpcMessageHeader_MessageNature >(nature_);
}
void SrpcMessageHeader::set_nature(::srpc::types::SrpcMessageHeader_MessageNature value) {
  
  nature_ = value;
  // @@protoc_insertion_point(field_set:srpc.types.SrpcMessageHeader.nature)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int SrpcString::kStringFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

SrpcString::SrpcString()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_srpc_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:srpc.types.SrpcString)
}
SrpcString::SrpcString(const SrpcString& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  string_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.string().size() > 0) {
    string_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.string_);
  }
  // @@protoc_insertion_point(copy_constructor:srpc.types.SrpcString)
}

void SrpcString::SharedCtor() {
  string_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _cached_size_ = 0;
}

SrpcString::~SrpcString() {
  // @@protoc_insertion_point(destructor:srpc.types.SrpcString)
  SharedDtor();
}

void SrpcString::SharedDtor() {
  string_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void SrpcString::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* SrpcString::descriptor() {
  protobuf_srpc_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_srpc_2eproto::file_level_metadata[1].descriptor;
}

const SrpcString& SrpcString::default_instance() {
  protobuf_srpc_2eproto::InitDefaults();
  return *internal_default_instance();
}

SrpcString* SrpcString::New(::google::protobuf::Arena* arena) const {
  SrpcString* n = new SrpcString;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void SrpcString::Clear() {
// @@protoc_insertion_point(message_clear_start:srpc.types.SrpcString)
  string_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

bool SrpcString::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:srpc.types.SrpcString)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string string = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_string()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->string().data(), this->string().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "srpc.types.SrpcString.string"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:srpc.types.SrpcString)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:srpc.types.SrpcString)
  return false;
#undef DO_
}

void SrpcString::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:srpc.types.SrpcString)
  // string string = 1;
  if (this->string().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->string().data(), this->string().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "srpc.types.SrpcString.string");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->string(), output);
  }

  // @@protoc_insertion_point(serialize_end:srpc.types.SrpcString)
}

::google::protobuf::uint8* SrpcString::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic;  // Unused
  // @@protoc_insertion_point(serialize_to_array_start:srpc.types.SrpcString)
  // string string = 1;
  if (this->string().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->string().data(), this->string().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "srpc.types.SrpcString.string");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->string(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:srpc.types.SrpcString)
  return target;
}

size_t SrpcString::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:srpc.types.SrpcString)
  size_t total_size = 0;

  // string string = 1;
  if (this->string().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->string());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void SrpcString::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:srpc.types.SrpcString)
  GOOGLE_DCHECK_NE(&from, this);
  const SrpcString* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const SrpcString>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:srpc.types.SrpcString)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:srpc.types.SrpcString)
    MergeFrom(*source);
  }
}

void SrpcString::MergeFrom(const SrpcString& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:srpc.types.SrpcString)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from.string().size() > 0) {

    string_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.string_);
  }
}

void SrpcString::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:srpc.types.SrpcString)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SrpcString::CopyFrom(const SrpcString& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:srpc.types.SrpcString)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SrpcString::IsInitialized() const {
  return true;
}

void SrpcString::Swap(SrpcString* other) {
  if (other == this) return;
  InternalSwap(other);
}
void SrpcString::InternalSwap(SrpcString* other) {
  string_.Swap(&other->string_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata SrpcString::GetMetadata() const {
  protobuf_srpc_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_srpc_2eproto::file_level_metadata[1];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// SrpcString

// string string = 1;
void SrpcString::clear_string() {
  string_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
const ::std::string& SrpcString::string() const {
  // @@protoc_insertion_point(field_get:srpc.types.SrpcString.string)
  return string_.GetNoArena();
}
void SrpcString::set_string(const ::std::string& value) {
  
  string_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:srpc.types.SrpcString.string)
}
#if LANG_CXX11
void SrpcString::set_string(::std::string&& value) {
  
  string_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:srpc.types.SrpcString.string)
}
#endif
void SrpcString::set_string(const char* value) {
  
  string_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:srpc.types.SrpcString.string)
}
void SrpcString::set_string(const char* value, size_t size) {
  
  string_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:srpc.types.SrpcString.string)
}
::std::string* SrpcString::mutable_string() {
  
  // @@protoc_insertion_point(field_mutable:srpc.types.SrpcString.string)
  return string_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* SrpcString::release_string() {
  // @@protoc_insertion_point(field_release:srpc.types.SrpcString.string)
  
  return string_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void SrpcString::set_allocated_string(::std::string* string) {
  if (string != NULL) {
    
  } else {
    
  }
  string_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), string);
  // @@protoc_insertion_point(field_set_allocated:srpc.types.SrpcString.string)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int SrpcStringList::kStringFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

SrpcStringList::SrpcStringList()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_srpc_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:srpc.types.SrpcStringList)
}
SrpcStringList::SrpcStringList(const SrpcStringList& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      string_(from.string_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:srpc.types.SrpcStringList)
}

void SrpcStringList::SharedCtor() {
  _cached_size_ = 0;
}

SrpcStringList::~SrpcStringList() {
  // @@protoc_insertion_point(destructor:srpc.types.SrpcStringList)
  SharedDtor();
}

void SrpcStringList::SharedDtor() {
}

void SrpcStringList::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* SrpcStringList::descriptor() {
  protobuf_srpc_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_srpc_2eproto::file_level_metadata[2].descriptor;
}

const SrpcStringList& SrpcStringList::default_instance() {
  protobuf_srpc_2eproto::InitDefaults();
  return *internal_default_instance();
}

SrpcStringList* SrpcStringList::New(::google::protobuf::Arena* arena) const {
  SrpcStringList* n = new SrpcStringList;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void SrpcStringList::Clear() {
// @@protoc_insertion_point(message_clear_start:srpc.types.SrpcStringList)
  string_.Clear();
}

bool SrpcStringList::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:srpc.types.SrpcStringList)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated string string = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->add_string()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->string(this->string_size() - 1).data(),
            this->string(this->string_size() - 1).length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "srpc.types.SrpcStringList.string"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:srpc.types.SrpcStringList)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:srpc.types.SrpcStringList)
  return false;
#undef DO_
}

void SrpcStringList::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:srpc.types.SrpcStringList)
  // repeated string string = 1;
  for (int i = 0, n = this->string_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->string(i).data(), this->string(i).length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "srpc.types.SrpcStringList.string");
    ::google::protobuf::internal::WireFormatLite::WriteString(
      1, this->string(i), output);
  }

  // @@protoc_insertion_point(serialize_end:srpc.types.SrpcStringList)
}

::google::protobuf::uint8* SrpcStringList::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic;  // Unused
  // @@protoc_insertion_point(serialize_to_array_start:srpc.types.SrpcStringList)
  // repeated string string = 1;
  for (int i = 0, n = this->string_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->string(i).data(), this->string(i).length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "srpc.types.SrpcStringList.string");
    target = ::google::protobuf::internal::WireFormatLite::
      WriteStringToArray(1, this->string(i), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:srpc.types.SrpcStringList)
  return target;
}

size_t SrpcStringList::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:srpc.types.SrpcStringList)
  size_t total_size = 0;

  // repeated string string = 1;
  total_size += 1 *
      ::google::protobuf::internal::FromIntSize(this->string_size());
  for (int i = 0, n = this->string_size(); i < n; i++) {
    total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
      this->string(i));
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void SrpcStringList::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:srpc.types.SrpcStringList)
  GOOGLE_DCHECK_NE(&from, this);
  const SrpcStringList* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const SrpcStringList>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:srpc.types.SrpcStringList)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:srpc.types.SrpcStringList)
    MergeFrom(*source);
  }
}

void SrpcStringList::MergeFrom(const SrpcStringList& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:srpc.types.SrpcStringList)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  string_.MergeFrom(from.string_);
}

void SrpcStringList::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:srpc.types.SrpcStringList)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SrpcStringList::CopyFrom(const SrpcStringList& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:srpc.types.SrpcStringList)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SrpcStringList::IsInitialized() const {
  return true;
}

void SrpcStringList::Swap(SrpcStringList* other) {
  if (other == this) return;
  InternalSwap(other);
}
void SrpcStringList::InternalSwap(SrpcStringList* other) {
  string_.UnsafeArenaSwap(&other->string_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata SrpcStringList::GetMetadata() const {
  protobuf_srpc_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_srpc_2eproto::file_level_metadata[2];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// SrpcStringList

// repeated string string = 1;
int SrpcStringList::string_size() const {
  return string_.size();
}
void SrpcStringList::clear_string() {
  string_.Clear();
}
const ::std::string& SrpcStringList::string(int index) const {
  // @@protoc_insertion_point(field_get:srpc.types.SrpcStringList.string)
  return string_.Get(index);
}
::std::string* SrpcStringList::mutable_string(int index) {
  // @@protoc_insertion_point(field_mutable:srpc.types.SrpcStringList.string)
  return string_.Mutable(index);
}
void SrpcStringList::set_string(int index, const ::std::string& value) {
  // @@protoc_insertion_point(field_set:srpc.types.SrpcStringList.string)
  string_.Mutable(index)->assign(value);
}
#if LANG_CXX11
void SrpcStringList::set_string(int index, ::std::string&& value) {
  // @@protoc_insertion_point(field_set:srpc.types.SrpcStringList.string)
  string_.Mutable(index)->assign(std::move(value));
}
#endif
void SrpcStringList::set_string(int index, const char* value) {
  string_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:srpc.types.SrpcStringList.string)
}
void SrpcStringList::set_string(int index, const char* value, size_t size) {
  string_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:srpc.types.SrpcStringList.string)
}
::std::string* SrpcStringList::add_string() {
  // @@protoc_insertion_point(field_add_mutable:srpc.types.SrpcStringList.string)
  return string_.Add();
}
void SrpcStringList::add_string(const ::std::string& value) {
  string_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:srpc.types.SrpcStringList.string)
}
#if LANG_CXX11
void SrpcStringList::add_string(::std::string&& value) {
  string_.Add()->assign(std::move(value));
  // @@protoc_insertion_point(field_add:srpc.types.SrpcStringList.string)
}
#endif
void SrpcStringList::add_string(const char* value) {
  string_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:srpc.types.SrpcStringList.string)
}
void SrpcStringList::add_string(const char* value, size_t size) {
  string_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:srpc.types.SrpcStringList.string)
}
const ::google::protobuf::RepeatedPtrField< ::std::string>&
SrpcStringList::string() const {
  // @@protoc_insertion_point(field_list:srpc.types.SrpcStringList.string)
  return string_;
}
::google::protobuf::RepeatedPtrField< ::std::string>*
SrpcStringList::mutable_string() {
  // @@protoc_insertion_point(field_mutable_list:srpc.types.SrpcStringList.string)
  return &string_;
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace types
}  // namespace srpc

// @@protoc_insertion_point(global_scope)
